from .waveguide import WaveGuide
from .waveguide_nn import WaveGuideWithPINNs

from .slab_waveguide import SlabWaveguide
from .slab_waveguide_FD import SlabWaveguideWithFD
from .slab_waveguide_nn import SlabWaveguideWithPINNs

from .buried_channel_waveguide import BuriedChannelWaveguide
from .buried_channel_waveguide_nn import BuriedChannelWaveguideWithPINNs
from .buried_channel_waveguide_fd import BuriedChannelWaveguideWithFD

from .rib_waveguide import RibWaveguide
from .rib_waveguide_nn import RibWaveguideWithPINNs
from .rib_waveguide_fd import RibWaveguideWithFD